# -*- coding: utf-8 -*-
"""สตอรีบอร์ดของวิดีโอแนะนำระบบ — แยกเนื้อหาออกจากตัวสร้างวิดีโอ"""

# แต่ละฉากกำหนดความยาวเป็นวินาที ตัวสร้างจะคำนวณเวลาเริ่มให้เอง
STORYBOARD_TH = {
    "lang": "th",
    "brand": "PaynEat POS",
    "outro_note": "ภาพทั้งหมดมาจากแอปจริง เรนเดอร์อัตโนมัติจากโค้ดล่าสุด",
    "scenes": [
        {
            "type": "title",
            "duration": 5.0,
            "title": "PaynEat POS",
            "subtitle": "ระบบขายหน้าร้านสำหรับร้านอาหาร",
            "note": "Flutter (GetX + Clean Architecture)  ·  Node.js + Express + SQLite + Socket.IO",
        },
        {
            "type": "bullets",
            "duration": 7.0,
            "kicker": "โจทย์",
            "title": "ปัญหาที่ระบบนี้แก้",
            "items": [
                ("ออเดอร์ตกหล่น", "ตั๋วกระดาษหาย สื่อสารผิด ต้องกลับไปถามลูกค้าใหม่"),
                ("บิลคำนวณพลาด", "ส่วนลด Service Charge และ VAT คิดไม่เหมือนกันทุกครั้ง"),
                ("ไม่รู้ยอดจนสิ้นเดือน", "กว่าจะเห็นตัวเลขก็สายเกินกว่าจะแก้อะไรได้"),
            ],
        },
        {
            "type": "roles",
            "duration": 6.5,
            "kicker": "โค้ดชุดเดียว",
            "title": "ครอบคลุมทุกคนในร้าน",
            "items": [
                ("พนักงานเสิร์ฟ", "มือถือ / แท็บเล็ต"),
                ("ครัว", "แท็บเล็ต / จอใหญ่"),
                ("แคชเชียร์", "แท็บเล็ต / เว็บ"),
                ("ผู้จัดการ", "เว็บ"),
            ],
        },
        {
            "type": "shot",
            "duration": 6.0,
            "image": "phone-02-tables.png",
            "frame": "phone",
            "step": "01",
            "title": "เปิดผังโต๊ะ",
            "caption": "เห็นทั้งร้านในจอเดียว โต๊ะไหนว่าง โต๊ะไหนค้างยอดเท่าไหร่",
            "badge": "อัปเดตเรียลไทม์ทุกเครื่อง",
        },
        {
            "type": "shot",
            "duration": 5.5,
            "image": "phone-03-order-taking.png",
            "frame": "phone",
            "step": "02",
            "title": "เลือกเมนู",
            "caption": "ค้นหาและกรองหมวดหมู่ในเครื่อง กดสลับหมวดได้ลื่นแม้เน็ตไม่ดี",
            "badge": "เมนูของหมดกดไม่ได้",
        },
        {
            "type": "shot",
            "duration": 6.0,
            "image": "phone-04-option-sheet.png",
            "frame": "phone",
            "step": "03",
            "title": "ตัวเลือกเสริม",
            "caption": "ระดับความเผ็ด ของเพิ่ม และโน้ตถึงครัว บันทึกได้ครบในขั้นตอนเดียว",
            "badge": "กลุ่มที่บังคับเลือก ข้ามไม่ได้",
        },
        {
            "type": "shot",
            "duration": 6.0,
            "image": "phone-05-cart.png",
            "frame": "phone",
            "step": "04",
            "title": "ยืนยันออเดอร์",
            "caption": "เห็นยอดรวม Service Charge และ VAT ตั้งแต่ยังไม่ปิดบิล",
            "badge": "รายการซ้ำถูกยุบให้อัตโนมัติ",
        },
        {
            "type": "shot",
            "duration": 8.0,
            "image": "tablet-14-kitchen.png",
            "frame": "screen",
            "step": "05",
            "title": "ตั๋วเด้งเข้าครัวทันที",
            "caption": "ไม่ต้องพิมพ์ ไม่ต้องกดรีเฟรช แบ่ง 3 คอลัมน์ตามสถานะงาน",
            "badge": "เตือนจานที่รอเกิน 15 นาที",
        },
        {
            "type": "shot",
            "duration": 5.5,
            "image": "tablet-15-order-detail.png",
            "frame": "screen",
            "step": "06",
            "title": "ติดตามทีละจาน",
            "caption": "รู้ว่าจานไหนอยู่ในครัว จานไหนพร้อมยกออกไปเสิร์ฟ",
            "badge": "จานที่ครัวเริ่มทำแล้ว แก้ไม่ได้",
        },
        {
            "type": "shot",
            "duration": 7.5,
            "image": "tablet-16-checkout.png",
            "frame": "screen",
            "step": "07",
            "title": "เก็บเงิน",
            "caption": "แยกจ่ายได้ เช่น QR ก่อนบางส่วน ที่เหลือจ่ายเงินสด",
            "badge": "คำนวณเงินทอนให้ทันที",
        },
        {
            "type": "shot",
            "duration": 5.5,
            "image": "phone-10-receipt.png",
            "frame": "phone",
            "step": "08",
            "title": "ออกใบเสร็จ",
            "caption": "แยกส่วนลด Service Charge และ VAT ชัดเจน พร้อมต่อเครื่องพิมพ์",
            "badge": "โต๊ะกลับมาว่างอัตโนมัติ",
        },
        {
            "type": "shot",
            "duration": 7.5,
            "image": "web-18-dashboard.png",
            "frame": "browser",
            "step": "09",
            "title": "ผู้จัดการเห็นยอดทันที",
            "caption": "ยอดขายวันนี้ ช่วงเวลาที่ลูกค้าเยอะ และเมนูขายดี ในหน้าเดียว",
            "badge": "อัปเดตทุกครั้งที่ปิดบิล",
        },
        {
            "type": "shot",
            "duration": 5.5,
            "image": "web-24-reports.png",
            "frame": "browser",
            "step": "10",
            "title": "รายงานย้อนหลัง",
            "caption": "เลือกช่วงวันที่เอง แยกยอดอาหาร ส่วนลด และภาษีให้เห็นที่มา",
            "badge": None,
        },
        {
            "type": "shot",
            "duration": 5.5,
            "image": "web-21-menu-management.png",
            "frame": "browser",
            "step": "11",
            "title": "จัดการเมนูเอง",
            "caption": "ปิดเมนูที่ของหมดด้วยสวิตช์เดียว มีผลทุกเครื่องทันที",
            "badge": None,
        },
        {
            "type": "stats",
            "duration": 7.0,
            "kicker": "เบื้องหลัง",
            "title": "สร้างมาให้ดูแลต่อได้",
            "items": [
                ("82", "เทสต์อัตโนมัติ"),
                ("3 ชั้น", "Clean Architecture"),
                ("31", "API endpoints"),
                ("1", "โค้ดเบส ทุกอุปกรณ์"),
            ],
            "note": "แยก domain / data / presentation ทำให้สลับแหล่งข้อมูลได้โดยไม่แตะหน้าจอ",
        },
        {
            "type": "outro",
            "duration": 6.5,
            "title": "ลองใช้งานได้เลย",
            "lines": [
                "docker compose up --build",
                "หรือ  cd backend && npm run dev   +   cd app && flutter run",
            ],
            "note": "github.com/SuruchBoss/PaynEat",
        },
    ],
}

STORYBOARD_EN = {
    "lang": "en",
    "brand": "PaynEat POS",
    "outro_note": "Every frame rendered from the working system, not a mock-up",
    "scenes": [
        {
            "type": "title",
            "duration": 5.0,
            "title": "PaynEat POS",
            "subtitle": "Point-of-Sale built for restaurants",
            "note": "One system across the phones, tablets and computers your team already uses",
        },
        {
            "type": "bullets",
            "duration": 7.0,
            "kicker": "THE PROBLEM",
            "title": "What it fixes",
            "items": [
                ("Orders get lost", "Paper tickets go missing and the table has to be asked again"),
                ("Bills do not add up", "Discounts, service charge and VAT applied differently every time"),
                ("Numbers arrive too late", "By month end it is too late to act on them"),
            ],
        },
        {
            "type": "roles",
            "duration": 6.5,
            "kicker": "ONE SYSTEM",
            "title": "For everyone on the floor",
            "items": [
                ("Servers", "Phone / tablet"),
                ("Kitchen", "Tablet / wall screen"),
                ("Cashier", "Tablet / computer"),
                ("Manager", "Web browser"),
            ],
        },
        {
            "type": "shot",
            "duration": 6.0,
            "image": "phone-02-tables.png",
            "frame": "phone",
            "step": "01",
            "title": "Open the floor plan",
            "caption": "The whole dining room at a glance — what is free and what each table owes",
            "badge": "Updates on every device",
        },
        {
            "type": "shot",
            "duration": 5.5,
            "image": "phone-03-order-taking.png",
            "frame": "phone",
            "step": "02",
            "title": "Pick the dishes",
            "caption": "Search and category filters stay responsive even on weak restaurant Wi-Fi",
            "badge": "Sold-out dishes cannot be ordered",
        },
        {
            "type": "shot",
            "duration": 6.0,
            "image": "phone-04-option-sheet.png",
            "frame": "phone",
            "step": "03",
            "title": "Options and requests",
            "caption": "Spice level, paid extras and a note to the kitchen — captured in one step",
            "badge": "Required choices cannot be skipped",
        },
        {
            "type": "shot",
            "duration": 6.0,
            "image": "phone-05-cart.png",
            "frame": "phone",
            "step": "04",
            "title": "Confirm the order",
            "caption": "Service charge and VAT are visible before the bill is ever closed",
            "badge": "Identical items combined automatically",
        },
        {
            "type": "shot",
            "duration": 8.0,
            "image": "tablet-14-kitchen.png",
            "frame": "screen",
            "step": "05",
            "title": "The kitchen sees it instantly",
            "caption": "Nothing to print, nothing to refresh — three columns by stage of work",
            "badge": "Dishes waiting over 15 minutes flagged",
        },
        {
            "type": "shot",
            "duration": 5.5,
            "image": "tablet-15-order-detail.png",
            "frame": "screen",
            "step": "06",
            "title": "Track it dish by dish",
            "caption": "Know what is still cooking and what is ready to carry out",
            "badge": "Cooking dishes cannot be edited away",
        },
        {
            "type": "shot",
            "duration": 7.5,
            "image": "tablet-16-checkout.png",
            "frame": "screen",
            "step": "07",
            "title": "Take payment",
            "caption": "Split payments as standard — part on QR, the rest in cash",
            "badge": "Change calculated as you type",
        },
        {
            "type": "shot",
            "duration": 5.5,
            "image": "phone-10-receipt.png",
            "frame": "phone",
            "step": "08",
            "title": "Issue the receipt",
            "caption": "Discount, service charge and VAT on separate lines, ready to print",
            "badge": "Table released automatically",
        },
        {
            "type": "shot",
            "duration": 7.5,
            "image": "web-18-dashboard.png",
            "frame": "browser",
            "step": "09",
            "title": "Owners see it as it happens",
            "caption": "Today's takings, your real rush hours and best sellers on one screen",
            "badge": "Refreshes as bills close",
        },
        {
            "type": "shot",
            "duration": 5.5,
            "image": "web-24-reports.png",
            "frame": "browser",
            "step": "10",
            "title": "Look back over any period",
            "caption": "Food revenue separated from discounts and tax, so the net figure is traceable",
            "badge": None,
        },
        {
            "type": "shot",
            "duration": 5.5,
            "image": "web-21-menu-management.png",
            "frame": "browser",
            "step": "11",
            "title": "Manage the menu yourself",
            "caption": "One switch takes a dish off sale across every device",
            "badge": None,
        },
        {
            "type": "stats",
            "duration": 7.0,
            "kicker": "UNDER THE HOOD",
            "title": "Built to be maintained",
            "items": [
                ("82", "automated checks"),
                ("3", "architectural layers"),
                ("31", "API endpoints"),
                ("1", "codebase, every device"),
            ],
            "note": "Runs entirely on your own network — an internet outage does not stop service",
        },
        {
            "type": "outro",
            "duration": 6.5,
            "title": "Try it yourself",
            "lines": [
                "docker compose up --build",
                "or  cd backend && npm run dev   +   cd app && flutter run",
            ],
            "note": "github.com/SuruchBoss/PaynEat",
        },
    ],
}
